#!/usr/bin/env python

import sys

def process_fasta(input_file_name):
  """
  do the processing of your fasta file here
  """
  sys.stderr.write(f"processing input file {input_file_name}\n")


if __name__ == "__main__":
  input_file_name = sys.argv[1]
  process_fasta(input_file_name)
